[package]
name = "bound-variable"
version = "0.1.0"
authors = ["Carlos Scheidegger <cscheid@cs.arizona.edu>"]
edition = "2018"

[dependencies]
byteorder="1.2.7"
rocket="0.4.0-rc.2"
serde="1.0.80"
bincode="1.0.1"
serde_derive = "1.0.80"
